// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 The generator-release-notes Authors

package plugin

import (
	"testing"

	"github.com/stretchr/testify/require"
)

func TestGeneratorGenerate(t *testing.T) {
	t.Parallel()

	output := New().Generate(ReleaseContext{
		Version:        "1.3.0",
		CurrentVersion: "1.2.0",
		Commits: []string{
			"feat: add new feature",
			"fix: resolve issue with X",
			"docs: update README",
			"feat!: remove deprecated endpoint",
		},
	})

	require.Equal(t, "## v1.3.0\n\n## What's Changed\n\n### Features\n- feat: add new feature\n- BREAKING: feat!: remove deprecated endpoint\n\n### Bug Fixes\n- fix: resolve issue with X\n\n### Other\n- docs: update README\n\n**Full Changelog**: v1.2.0...v1.3.0", output)
}

func TestGeneratorGenerateWithoutCommitsUsesFallback(t *testing.T) {
	t.Parallel()

	output := New().Generate(ReleaseContext{Branch: "main"})

	require.Equal(t, "## What's Changed\n\n- No notable changes\n\n_Target branch: main_", output)
}

func TestClassifyCommit(t *testing.T) {
	t.Parallel()

	section, line := classifyCommit("fix: patch bug\n\nBREAKING CHANGE: behavior changed")
	require.Equal(t, bugFixesSection, section)
	require.Equal(t, "BREAKING CHANGE: behavior changed", line)

	section, line = classifyCommit("notes from manual release")
	require.Equal(t, otherChangesSection, section)
	require.Equal(t, "notes from manual release", line)
}

func TestGeneratorGenerateWithSignature(t *testing.T) {
	t.Parallel()

	output := New().Generate(ReleaseContext{
		Version: "1.3.0",
		Commits: []string{"feat: add new feature"},
	}, GenerateOptions{Signature: true})

	require.Contains(t, output, "---\n*Generated by [semrel.io](https://semrel.io)*")
}

func TestDetectAIAuthors(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name   string
		commit string
		want   []string
	}{
		{
			name:   "copilot",
			commit: "feat: thing\n\nCo-authored-by: Copilot <x@y.com>",
			want:   []string{"GitHub Copilot"},
		},
		{
			name:   "no trailer",
			commit: "fix: ordinary fix",
			want:   nil,
		},
	}

	for _, tt := range tests {
		tt := tt
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()
			require.Equal(t, tt.want, detectAIAuthors(tt.commit))
		})
	}
}

func TestGeneratorAIDisclosureBadge(t *testing.T) {
	t.Parallel()

	opts := DefaultGenerateOptions()
	opts.AIDisclosure = true

	output := New().Generate(ReleaseContext{
		Version: "1.3.0",
		Commits: []string{
			"feat: add feature\n\nCo-authored-by: Copilot <x@y.com>",
			"fix: plain fix",
		},
	}, opts)

	require.Contains(t, output, "🤖")
	require.NotContains(t, output, "AI-Assisted Contributions")
}

func TestGeneratorAIDisclosureSection(t *testing.T) {
	t.Parallel()

	opts := DefaultGenerateOptions()
	opts.AIDisclosure = true
	opts.AIDisclosureSection = true

	output := New().Generate(ReleaseContext{
		Version: "1.3.0",
		Commits: []string{
			"feat: add feature\n\nCo-authored-by: Copilot <x@y.com>",
		},
	}, opts)

	require.Contains(t, output, "AI-Assisted Contributions")
	require.Contains(t, output, "Co-authored with **GitHub Copilot**")
	require.Contains(t, output, "L-08 §8")
}

func TestGeneratorAIDisclosureOffByDefault(t *testing.T) {
	t.Parallel()

	output := New().Generate(ReleaseContext{
		Version: "1.3.0",
		Commits: []string{
			"feat: add feature\n\nCo-authored-by: Copilot <x@y.com>",
		},
	})

	require.NotContains(t, output, "🤖")
	require.NotContains(t, output, "AI-Assisted Contributions")
}
