// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2026 The generator-release-notes Authors

package plugin

import (
	"testing"

	"github.com/stretchr/testify/require"
)

func TestGeneratorGenerate(t *testing.T) {
	t.Parallel()

	output := New().Generate(ReleaseContext{
		Version:        "1.3.0",
		CurrentVersion: "1.2.0",
		Commits: []string{
			"feat: add new feature",
			"fix: resolve issue with X",
			"docs: update README",
			"feat!: remove deprecated endpoint",
		},
	})

	require.Equal(t, "## v1.3.0\n\n## What's Changed\n\n### Features\n- feat: add new feature\n- BREAKING: feat!: remove deprecated endpoint\n\n### Bug Fixes\n- fix: resolve issue with X\n\n### Other\n- docs: update README\n\n**Full Changelog**: v1.2.0...v1.3.0", output)
}

func TestGeneratorGenerateWithoutCommitsUsesFallback(t *testing.T) {
	t.Parallel()

	output := New().Generate(ReleaseContext{Branch: "main"})

	require.Equal(t, "## What's Changed\n\n- No notable changes\n\n_Target branch: main_", output)
}

func TestClassifyCommit(t *testing.T) {
	t.Parallel()

	section, line := classifyCommit("fix: patch bug\n\nBREAKING CHANGE: behavior changed", DefaultGenerateOptions())
	require.Equal(t, bugFixesSection, section)
	require.Equal(t, "BREAKING CHANGE: behavior changed", line)

	section, line = classifyCommit("notes from manual release", DefaultGenerateOptions())
	require.Equal(t, otherChangesSection, section)
	require.Equal(t, "notes from manual release", line)
}

func TestGeneratorGenerateWithCustomSections(t *testing.T) {
	t.Parallel()

	opts := DefaultGenerateOptions()
	opts.Sections = []SectionRule{
		{Type: "feat", Section: "Highlights"},
		{Type: "fix", Section: "Bugfixes"},
		{Type: "docs", Hidden: true},
	}

	output := New().Generate(ReleaseContext{
		Version: "1.3.0",
		Commits: []string{
			"feat: add new feature",
			"fix: resolve issue with X",
			"docs: update README",
			"chore: tidy up",
		},
	}, opts)

	require.Equal(t, "## v1.3.0\n\n## What's Changed\n\n### Highlights\n- feat: add new feature\n\n### Bugfixes\n- fix: resolve issue with X\n\n### Other\n- chore: tidy up", output)
}

func TestGeneratorGenerateWithEmptyCustomSectionUsesFallback(t *testing.T) {
	t.Parallel()

	opts := DefaultGenerateOptions()
	opts.Sections = []SectionRule{{Type: "chore"}}

	output := New().Generate(ReleaseContext{
		Version: "1.3.0",
		Commits: []string{"chore: tidy up"},
	}, opts)

	require.Contains(t, output, "### Other")
	require.Contains(t, output, "chore: tidy up")
}

func TestFindSectionRuleIsCaseInsensitive(t *testing.T) {
	t.Parallel()

	rules := []SectionRule{{Type: "Feat", Section: "Features"}}
	rule, ok := findSectionRule(rules, "feat")
	require.True(t, ok)
	require.Equal(t, "Features", rule.Section)

	_, ok = findSectionRule(rules, "fix")
	require.False(t, ok)
}

func TestGeneratorGenerateWithSignature(t *testing.T) {
	t.Parallel()

	output := New().Generate(ReleaseContext{
		Version: "1.3.0",
		Commits: []string{"feat: add new feature"},
	}, GenerateOptions{Signature: true})

	require.Contains(t, output, "---\n*Generated by [semrel.io](https://semrel.io)*")
}

func TestDetectAIAuthors(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name   string
		commit string
		want   []string
	}{
		{
			name:   "copilot",
			commit: "feat: thing\n\nCo-authored-by: Copilot <x@y.com>",
			want:   []string{"GitHub Copilot"},
		},
		{
			name:   "no trailer",
			commit: "fix: ordinary fix",
			want:   nil,
		},
	}

	for _, tt := range tests {
		tt := tt
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()
			require.Equal(t, tt.want, detectAIAuthors(tt.commit))
		})
	}
}

func TestGeneratorAIDisclosureBadge(t *testing.T) {
	t.Parallel()

	opts := DefaultGenerateOptions()
	opts.AIDisclosure = true

	output := New().Generate(ReleaseContext{
		Version: "1.3.0",
		Commits: []string{
			"feat: add feature\n\nCo-authored-by: Copilot <x@y.com>",
			"fix: plain fix",
		},
	}, opts)

	require.Contains(t, output, "🤖")
	require.NotContains(t, output, "AI-Assisted Contributions")
}

func TestGeneratorAIDisclosureSection(t *testing.T) {
	t.Parallel()

	opts := DefaultGenerateOptions()
	opts.AIDisclosure = true
	opts.AIDisclosureSection = true

	output := New().Generate(ReleaseContext{
		Version: "1.3.0",
		Commits: []string{
			"feat: add feature\n\nCo-authored-by: Copilot <x@y.com>",
		},
	}, opts)

	require.Contains(t, output, "AI-Assisted Contributions")
	require.Contains(t, output, "Co-authored with **GitHub Copilot**")
	require.Contains(t, output, "L-08 §8")
}

func TestGeneratorAIDisclosureOffByDefault(t *testing.T) {
	t.Parallel()

	output := New().Generate(ReleaseContext{
		Version: "1.3.0",
		Commits: []string{
			"feat: add feature\n\nCo-authored-by: Copilot <x@y.com>",
		},
	})

	require.NotContains(t, output, "🤖")
	require.NotContains(t, output, "AI-Assisted Contributions")
}

func TestGeneratorNewContributors(t *testing.T) {
	t.Parallel()

	generator := New()
	ctx := ReleaseContext{
		Version:       "1.4.0",
		RepositoryURL: "https://github.com/SemRels/semrel",
		Commits:       []string{"feat: add login (#42)"},
	}

	t.Run("new contributors section rendered when contributors provided", func(t *testing.T) {
		t.Parallel()

		opts := DefaultGenerateOptions()
		opts.Contributors = []Contributor{
			{Name: "Alice", Login: "alice", PR: 42},
		}

		output := generator.Generate(ctx, opts)

		require.Contains(t, output, "### New Contributors")
		require.Contains(t, output, "[@alice](https://github.com/alice)")
		require.Contains(t, output, "[#42](https://github.com/SemRels/semrel/pull/42)")
	})

	t.Run("new contributors section skipped when contributors empty", func(t *testing.T) {
		t.Parallel()

		opts := DefaultGenerateOptions()
		opts.Contributors = nil

		output := generator.Generate(ctx, opts)

		require.NotContains(t, output, "New Contributors")
	})

	t.Run("new contributors section skipped when disabled", func(t *testing.T) {
		t.Parallel()

		opts := DefaultGenerateOptions()
		opts.NewContributors = false
		opts.Contributors = []Contributor{{Name: "Alice", Login: "alice"}}

		output := generator.Generate(ctx, opts)

		require.NotContains(t, output, "New Contributors")
	})

	t.Run("contributor without login uses plain name", func(t *testing.T) {
		t.Parallel()

		opts := DefaultGenerateOptions()
		opts.Contributors = []Contributor{{Name: "Alice Smith"}}

		output := generator.Generate(ctx, opts)

		require.Contains(t, output, "Alice Smith made their first contribution")
	})

	t.Run("MVP section rendered when enabled", func(t *testing.T) {
		t.Parallel()

		opts := DefaultGenerateOptions()
		opts.MVP = true
		opts.Contributors = []Contributor{
			{Name: "Alice", Login: "alice", PR: 42},
		}

		output := generator.Generate(ctx, opts)

		require.Contains(t, output, "### 🏆 MVP")
		require.Contains(t, output, "[@alice](https://github.com/alice) led the contributors this release.")
	})

	t.Run("MVP section skipped when disabled", func(t *testing.T) {
		t.Parallel()

		opts := DefaultGenerateOptions()
		opts.MVP = false
		opts.Contributors = []Contributor{{Name: "Alice", Login: "alice", PR: 42}}

		output := generator.Generate(ctx, opts)

		require.NotContains(t, output, "MVP")
	})
}
